### PR TITLE
django 1.8 compatibility

### PR DESCRIPTION
**Pull request by maccesch**
Solves #44

### CODE REVIEW

**Comment by maccesch** [comment]
The build failed only for python 2.6 and that is because of behave itself. It uses importlib. Maybe you should ditch the 2.6 tests since behave doesn't support it anymore

**Comment by ivancrneto** [comment]
actually behave supports 2.6, the problem is that when installing behave from requirements.txt, for some reason it is not installing behave dependencies for 2.6 (importlib and argparse), but if we download behave and run `setup.py install` it works. That is odd.

**Comment by ivancrneto** [comment]
it should work if you add 
` - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install importlib argparse; fi`
to install section in `.travis.yml`

**Comment by maccesch** [comment]
I stand corrected. Thanks @ivancrneto, that was it!

**Comment by ivancrneto** [comment]
:+1:

**Comment by ivancrneto** [comment]
shouldn't you add django 1.8 to travis build?

**Comment by maccesch** [comment]
You are absolutely right

**Pull request merged**
