### PR TITLE
support test for both sub dirs and entire project

### PR DESCRIPTION
**Pull request by guoqiao**
Before, you can only test app in current dir like this:

    ./manage.py test myapp

Now, you can test app in sub dirs like this:

    ./manage.py test apps.myapp

And, you can test entire project like this:

    ./manage.py test

### CODE REVIEW

**Comment by guoqiao** [comment]
No one merge?

**Comment by rwillmer** [comment]
Hi @guoqiao sorry for delay, I'm at a conference. Will check it later.

**Comment by rwillmer** [comment]
Hi @guoqiao this PR is failing in Travis. Can you fix it please? then I can merge it.

**Comment by guoqiao** [comment]
I will have a look soon, thanks.

**Comment by guoqiao** [comment]
@rwillmer where can I see the error message?

**Comment by guoqiao** [comment]
@rwillmer I made 3 commits, the first one failed,  but in the following commits, I already fixed it.  Did you mean I should squash them to one commit?

**Comment by rwillmer** [comment]
yes please

**Comment by guoqiao** [comment]
@rwillmer  squashed. Thanks for your job, my team is using this packages in a project, and we need to run tests in subdir and for whole project. Hope my patch can work and be merged.

**Comment by rwillmer** [comment]
Thanks for the PR, merged. Do you need me to push a new version to pypi?

**Comment by guoqiao** [comment]
@rwillmer: Not necessary yet, thanks.

**Pull request merged**
